language: python
matrix:
  include:
    - python: "3.7"
      env: TOX_ENV=black,flake8,mypy,py37
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "3.5"
      env: TOX_ENV=py35
    - python: "2.7"
      env: TOX_ENV=py27
    - python: pypy3
      env: TOX_ENV=pypy3
    - python: pypy
      env: TOX_ENV=pypy
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$TRAVIS_BUILD_DIR/.tox"
install:
  - pip install tox codecov
script:
  - tox -e $TOX_ENV -- --cov-report term-missing --cov=graphql_server
after_success:
  - codecov
deploy:
  provider: pypi
  on:
    branch: master
    tags: true
    python: 3.7
  skip_existing: true
  user: __token__
  password:
    secure: WcZf7AVMDzheXWUxNhZF/TUcyvyCdHZGyhHTakjBhUs8I8khSvlMPofaXTdN1Qn3WbHPK+IXeIPh/2NX0Le3Cdzp08Q/Tgrf9EZ4y02UrZxwSxtsUmjCVd8GaCsQnhR5t5cgrtw33OAf0O22rUnMXsFtw7xMIuCNTgFiYclNbHzYbvnJAEcY3qE8RBbP8zF5Brx+Bl49SjfVR3dJ7CBkjgC9scZjSBAo/yc64d506W59LOjfvXEiDtGUH2gxZNwNiteZtI3frMYqLRjS563SwEFlG36B8g0hBOj6FVpU+YXeImYXw3XFqC6dCvcwn1dAf/vUZ4IDiDIVf5KvFcyDx0ZwZlMSzqlkLVpSDGqPU+7Mx15NW00Yk2+Zs2ZWFMK+g5WtSehhrAWR6El3d0MRlDXKgt9QbCRyh8b2jPV/vQZN2FOBOg9V9a6IszOy/W1J81q39cLOroBhQF4mDFYTAQ5QpBVUyauAfB49QzXsmSWy2uOTsbgo+oAc+OGJ6q9vXCzNqHxhUvtDT9HIq4w5ixw9wqtpSf6n+l2F2RFl5SzHIR7Dt0m9Eg2Ig5NqSGlymz46ZcxpRjd4wVXALD4M8usqy35jGTeEXsqSTO98n3jwKTj/7Xi6GOZuBlwW+SGAjXQ0vzlWD3AEv0Jnh+4AH5UqWwBeD1skw8gtbjM4dos=
